### ISSUE TITLE
Főcím választása

### ISSUE THREAD

**Issue by petihegyi** [LxKiss/ResearchMethodology#4]

**Comment by miskolczim98** [comment]
Adtam most ideiglenes címet, de nyugodtan lehet kreatívabb, bőbeszédűbb.

**Comment by petihegyi** [comment]
Amúgy nem rossz, a 'korszerűsítés' szerintem viszont tuti nem jó szóválasztás mert elég korszerű a cucc is amiből kiindultunk :D

**Comment by miskolczim98** [comment]
Dinamikus decentralizált NP-Teljes Multi-Ágens rendszerek konfliktusmentes útkeresési dekompozionicálható problémáinak továbbfejlesztése polinominális futási idejü utasítás támogatásal ellátott Séta Megállás Megszámlálás and Csere algoritmus felhasználásával.

Ehhez mit szóltok?:DD
